interface CommonConstantsInterface {
  columnWidth: string;
  columnHeight: string;
  columnFlexShrink: number;
  width: string;
  height: string;
  sliderMin: number;
  sliderMax: number;
  sliderMargin: number;
  percentSign: string;
}

export const commonConstants: CommonConstantsInterface = {
  columnWidth: '100%',
  columnHeight: '100%',
  columnFlexShrink: 1,
  width: '100%',
  height: '100%',
  sliderMin: 55,
  sliderMax: 90,
  sliderMargin: 24,
  percentSign: '%'
};
