export const INDEX_ROUTE: string = 'pages/Index'

export const ROUTE_WELCOME: string = 'welcome'

export const ROUTE_CREATE_VAULT: string = 'createVault'

export const ROUTE_FILE_SUMMARY: string = 'fileSummary'

export const ROUTE_UNLOCK: string = 'unlock'

export const ROUTE_VAULT: string = 'vault'

export const ROUTE_SECURITY: string = 'security'

export const ROUTE_GENERATOR: string = 'generator'

export const ROUTE_SETTINGS: string = 'settings'

export const ROUTE_TEMPLATE: string = 'template'

export const ROUTE_ENTRY_EDIT: string = 'entryEdit'

export const ROUTE_ENTRY_DETAIL: string = 'entryDetail'
